### ISSUE TITLE
Price Data Discrepancies

### ISSUE THREAD

**Issue by rhamo** [msperlin/yfR#7] opened 2022-05-10 10:00 UTC
Hi msperlin,

I have been running multiple tests using individual, multiple and collection "SP500" tickers with yfR and found random discrepancies when comparing price data to Yahoo Finance Website (Historical Price Data) and BatchGetSymbols price data.

This example was conducted on AAPL for Weekly price data for the last 3 weeks.

```
Yahoo  Finance Website
AAPL Weekly Historical Price Data

Date 		  Open	        High	Low	Close *Adj close**	Volume
May 09, 2022	  154.93	155.83	151.49	152.06	152.06		131,419,200
May 02, 2022	  156.71	166.48	153.27	157.28	157.05		566,859,300
Apr 25, 2022	  161.12	166.20	155.38	157.65	157.42		541,536,700

BatchGetSymbols 
AAPL Weekly Price Data
Date 		  Open	        High	Low     Close  *Adj close**	Volume
May 09, 2022	  154.93	155.83	151.49	152.06	152.06		131,419,200
May 02, 2022	  156.71	166.48	153.27	157.28	157.28		566,859,300
Apr 25, 2022	  161.12	166.20	155.38	157.65	157.42		541,536,700

yfR 
AAPL Weekly Price Data
Date 		  Open	        High	Low     Close  *Adj close**	Volume
May 09, 2022	  154.93	155.83	151.49	152.06	152.06		131,419,200
May 02, 2022	  **156.01**	166.48	153.27	157.28	157.28		566,859,300
Apr 25, 2022	  **161.84**	166.20	155.38	157.65	157.42		541,536,700
```

These errors have also been discovered when using "freq_data" daily, weekly and monthly across multiple tickers and in this example alone appears to be an issue with the Open price. When I carried this test on all SP500 tickers approx 100 tickers has issues with the price data.

Please note in this example I have cross-checked AAPL weekly price data with stock charting software. The Yahoo Finance website and BatchGetSymbols is correct. yfR is incorrect.

Here is the R script I used for yfR:

```
library(yfR)
 
 tickers <- c("AAPL")
 
first_date <- Sys.Date() - 70
last_date <- Sys.Date()

 df_yf <- yf_get(
     tickers = tickers,
     first_date = first_date,
     last_date = last_date,
     freq_data = "weekly",
     bench_ticker = "^GSPC",
     how_to_aggregate = "last",
     do_complete_data = FALSE,
     thresh_bad_data = 0.75,
     do_cache = TRUE)
```

Kind regards,
Ron

**Comment by rhamo** [comment] 2022-05-26 22:16
More testing carried out on yfR's Daily, Weekly and Monthly price data. Open Price always seems to be problematic.
High, Low and Close seem to be stable?

**Comment by msperlin** [comment] 2022-05-27 11:49
Thanks @rhamo 
I need some time to investigate this. I find it very weird the data doesnt match between yfR and BatchGetSymbols. Did you execute the code in the same day?

**Comment by rhamo** [comment] 2022-05-27 21:54
Yes all executed within minutes of each other. 
Always seems to be incorrect Open price when using freq_data = Weekly, Monthly and Yearly.
I’m not sure how yfR calculates the open price compared to getsymbols but have compared yfR to getSymbols & BatchGetSymbols using over 20 tickers within the S&P 500 and all open prices are wrong.

**Comment by msperlin** [comment] 2022-05-31 17:45
So the problem is just for open prices when aggregating?  -- yfR calculates this by picking the first/last (see arg `how_to_aggregate`) date for week/monthly/year.

Can you share some code so that we are looking at the same issue?

**Comment by msperlin** [comment] 2022-06-20 17:13
thanks @rhamo 

Code wise, yes, there were some changes in between BatchGetSymbols and yfR, especially for aggregated data. My advice, stick with yfR which is the package I'll maintain moving forward. 
 
As for the difference of open prices, the raw data comes from Yahoo finance and I have no control over its quality. So I cannot check (or fix) anything related to raw data.

**Comment by msperlin** [comment] 2022-06-20 17:14
I'm closing this one as I dont see what I can do to improve the raw data.

**Closed by msperlin** 2022-06-20 17:14 UTC

**Comment by rhamo** [comment] 2022-06-25 23:27
I completely understand that you have no control over yahoo price data but is it possible to return the "aggregated data" code back to the BatchGetSymbols code for yfR? 
I assume people use this to retrieve stock O/H/L/C data to match what they see on all published stock candlestick charts?
I believe Yahoo's data is correct but it all comes down to how I word my script for "how_to_aggregate" = "first" or "last" which I believe is incorrect. 
Please know I do appreciate all your work @msperlin  I just don't understand why the Open and Close price can be so wrong due to the way I need to write my script.

**Comment by msperlin** [comment] 2022-06-27 20:37
The issue is that in BatchGetsymbols, the option "how_to_aggregate" = "first" was yielding the first Maximum in the column high_price (maximum of first day of year, for example), while yfR uses the maximum value whithin the interval (maximum highest price within the year), which is the right calculation. 

btw, you can see that in the code of `yf_get`:

![image](https://user-images.githubusercontent.com/10583352/176031171-c7385dde-19b9-4503-83d8-771e77e2ea72.png)

**Comment by rhamo** [comment] 2022-06-29 10:58
Refer to images below, how_to_aggregate = "last" code in yfR is different to BatchGetSymbols.
I believe the code used for how_to_aggregate = "last" , price.open and price.close prices in BatchGetSymbols is the correct code.

```
price.open = first(price.open)
price.close = last(price.close)
```


yfR
![Screen Shot 2022-06-29 at 8 50 30 pm](https://user-images.githubusercontent.com/74288576/176420268-a361b005-6cc3-42e7-b027-6c31472e347c.png)

BatchGetSymbols
![Screen Shot 2022-06-29 at 8 51 57 pm](https://user-images.githubusercontent.com/74288576/176420357-1735e14f-266e-4811-a4a2-d2254372e65f.png)

**Comment by msperlin** [comment] 2022-06-30 21:00
Thanks @rhamo. The code in yfR looks fine to me. I believe you can have it both ways, depending on your data needs for high/open/low prices. 

If you really need a different type of aggregation offered by yfR, you can download the daily data and aggregate outside of yf_get.
